<a href="https://colab.research.google.com/github/Dain777666/ESAA_25-1/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
#configuration: NumPy가 사용하는 라이브러리와 최적화 정보를 출력함

print("NumPy Version:", np.__version__)
np.show_config()

NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
#null vector: 모든 요소가 0으로 채워진 벡터

null_vector = np.zeros(10) #np.zeros(): 모든 요소가 0인 배열을 생성하는 넘파이 함수
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [11]:
arr = np.zeros((2,4)) #float64 element: 8bytes, so 8*8=64 bytes.
print(arr.nbytes)

##manual calculation##
memory_size = arr.itemsize * arr.size
#.itemsize: default is 8bytes for folat64
#.size: total number of elements
print(memory_size)

64
64


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
reversed_vector = vector[::-1] #전체 배열을 선택하여, 역순으로 출력
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
matrix_3x3 = np.arange(9).reshape(3,3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
array = np.array([1,2,0,0,4,0])
nonzero_indices = np.nonzero(array) #np.nonzero(): 넘파이 배열에서 0이 아닌 값의 인덱스를 반환
print(nonzero_indices)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [3]:
identity_matrix = np.eye(3)
#identity matrix(단위행렬): 주대각선이 1이고 나머지는 0으로 채워진 정사각 행렬
#np.eye(): 넘파이에서 단위행렬을 생성하는 함수
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [4]:
random_array = np.random.random((3,3,3))
#np.random.random(): 0과 1 사이의 난수를 생성하는 함수
print(random_array)

[[[0.69438894 0.25923208 0.87426058]
  [0.02694437 0.45175947 0.71169144]
  [0.90368483 0.47005562 0.70656085]]

 [[0.33523241 0.9429301  0.29225124]
  [0.60435712 0.64572351 0.04037888]
  [0.02331778 0.44692512 0.32361659]]

 [[0.28193939 0.37062546 0.4185144 ]
  [0.53160101 0.79471755 0.11404323]
  [0.16733307 0.07191947 0.21332796]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [5]:
random_10x10 = np.random.rand(10,10)
#np.random.rand(): 0과 1 사이의 난수를 생성하는 함수
##np.random.random vs np.random.rand
#기능은 동일하지만, rand()는 개별 인자, random()은 튜플로 크기를 전달해야 한다는 차이가 있음.
min_value = np.min(random_10x10)
max_value = np.max(random_10x10)

print("Random 10x10 Array:\n", random_10x10)
print("\nMinimum Value:", min_value)
print("\nMaximum Value:", max_value)

Random 10x10 Array:
 [[0.34682002 0.52487011 0.61030355 0.7885605  0.52525845 0.34847056
  0.05600011 0.22123678 0.10719349 0.06595279]
 [0.02302701 0.60190216 0.34196049 0.55970717 0.34696493 0.13471343
  0.71018626 0.28711083 0.08497705 0.44279531]
 [0.01663722 0.05373221 0.72375807 0.33623847 0.82825612 0.28848079
  0.50105456 0.74577302 0.43456066 0.68885432]
 [0.11391674 0.76646894 0.16799408 0.5893772  0.61301828 0.11535826
  0.40305197 0.22704745 0.60754675 0.95616869]
 [0.00324101 0.5422877  0.42829925 0.59070103 0.31949108 0.15905434
  0.3777341  0.27432381 0.45686556 0.53825928]
 [0.16786129 0.61841075 0.75839817 0.26600596 0.03690343 0.74122763
  0.92138438 0.03836857 0.0506344  0.64461034]
 [0.43606772 0.65781265 0.44676054 0.52778047 0.35530812 0.49303769
  0.75614767 0.05025854 0.88770864 0.62091111]
 [0.41026668 0.64676439 0.84761999 0.17785389 0.52838741 0.28852748
  0.52168306 0.42148362 0.13416619 0.43911928]
 [0.11852192 0.17362351 0.92480505 0.74393149 0.55801688 0.

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [6]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)

print("Random Vector:\n", random_vector)
print("\nMean Value:", mean_value)

Random Vector:
 [0.16254863 0.54354346 0.19522137 0.12523193 0.41208292 0.02613537
 0.7060567  0.97365616 0.23638198 0.00568848 0.95738164 0.0495831
 0.46951016 0.43352311 0.59843973 0.08734385 0.93695879 0.45454878
 0.8603889  0.05271368 0.88065636 0.18337718 0.83849427 0.24810673
 0.50042133 0.86297813 0.58972493 0.37493796 0.57441878 0.89362556]

Mean Value: 0.47445599882181017


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [7]:
rows, cols = 5, 5
array = np.zeros((rows, cols), dtype=int) #정수형 지정해주기
array[0,:] = 1 #top border
array[-1, :] = 1 #bottom border
array[:, 0] = 1 #left border
array[:, -1] = 1 #right border

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

np.nan은 "Not a Number" (숫자가 아님) 을 의미하는 특별한 값이다. NumPy에서 결측값(missing value)이나 정의되지 않은 연산의 결과를 나타낼 때 사용된다.


✅np.nan의 주요 특징
*   np.nan은 자신과 같지 않다. (np.nan != np.nan)
*   np.nan이 포함된 연산은 결과도 np.nan이 된다.
*   np.nan이 들어간 배열에서 비교 연산을 하면 False가 나온다.
*   평균, 합을 구할 때 nan이 있으면 nan이 나오므로, np.nanmean(), np.nansum()을 사용한다.





< 0.3 == 3 * 0.1 결과가 False인 이유 >

✅ 이유: 부동소수점 오차(Floating-point precision error) 때문이다. 3 * 0.1을 실제로 계산하면 0.30000000000000004 가 되어 0.3과 같지 않다.


nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [8]:
matrix = np.zeros((5,5), dtype=int)
matrix += np.diag([1,2,3,4], k=-1) #대각선 아래(k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1 #홀수 행의 짝수 열에 1을 배치
checkerboard[::2, 1::2] = 1 #짝수 행의 홀수 열에 1을 배치
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


✅**기본적인 슬라이싱 문법**

array[start:end:step, start:end:step]


*   start: 시작 인덱스
*   end: 종료 인덱스
*   step: 간격(생략하면 기본값 1)








#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [10]:
shape = (6,7,8)
index = np.unravel_index(99, shape)
#np.unravel_index(): 1차원 인덱스를 다차원 인덱스로 변환하는 함수
print(index)

(1, 5, 3)


⭐계산과정

(1) z 인덱스 찾기 (가장 안쪽 차원)

 99 % 8 = 3 → z = 3

(z는 8개의 요소마다 한 바퀴 도니까 나머지가 z 위치)

(2) y 인덱스 찾기 (중간 차원)

(99 // 8) % 7 = (12) % 7 = 5 → y = 5
(y는 7개의 z 그룹마다 한 바퀴)

(3) x 인덱스 찾기 (가장 바깥 차원)

99 // (8 × 7) = 1 → x = 1
(x는 8×7개의 요소마다 한 바퀴 도니까 1회 반복)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [11]:
X = np.random.rand(5,5)
mean_X = np.mean(X)
std_X = np.std(X)
Z = (X - mean_X) / std_X

print("Original Matrix:\n", X)
print("\nMean:", mean_X)
print("Standard Deviation:", std_X)
print("\nNormalized Matrix:\n", Z)

Original Matrix:
 [[0.01938683 0.71235745 0.06049199 0.11410954 0.54725991]
 [0.42253014 0.55430458 0.6832069  0.81839294 0.84049041]
 [0.87217701 0.8218894  0.5851703  0.09719163 0.80290092]
 [0.62793773 0.90898765 0.45356125 0.8467222  0.54129726]
 [0.3835408  0.35536065 0.31011018 0.862607   0.27895306]]

Mean: 0.5408375096346241
Standard Deviation: 0.27571854031881354

Normalized Matrix:
 [[-1.89124270e+00  6.22083460e-01 -1.74215894e+00 -1.54769414e+00
   2.32933091e-02]
 [-4.29087461e-01  4.88435315e-02  5.16357707e-01  1.00666218e+00
   1.08680722e+00]
 [ 1.20173094e+00  1.01934347e+00  1.60790031e-01 -1.60905349e+00
   9.50474395e-01]
 [ 3.15902654e-01  1.33523898e+00 -3.16541135e-01  1.10940922e+00
   1.66747892e-03]
 [-5.70497395e-01 -6.72703613e-01 -8.36821972e-01  1.16702158e+00
  -9.49825322e-01]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [12]:
#RGBA 생상을 저장할 사용자 정의 dtype 생성
rgba_dtype = np.dtype([
    ('R', np.ubyte),
    ('G', np.ubyte),
    ('B', np.ubyte),
    ('A', np.ubyte)
])

#위에서 만든 dtype을 사용해 색상 배열 생성
colors = np.array([
    (255, 0, 0, 255),   # 빨강 (Red)
    (0, 255, 0, 255),   # 초록 (Green)
    (0, 0, 255, 255),   # 파랑 (Blue)
    (255, 255, 0, 255), # 노랑 (Yellow)
    (0, 0, 0, 128)      # 반투명 검정 (Semi-transparent Black)
], dtype=rgba_dtype)

# 3️⃣ 배열 출력
print(colors)

# 4️⃣ 특정 색상의 값 출력
print("\n첫 번째 색상 (Red):", colors[0])
print("첫 번째 색상의 R 값:", colors[0]['R'])
print("마지막 색상의 Alpha 값:", colors[-1]['A'])

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255) (  0,   0,   0, 128)]

첫 번째 색상 (Red): (255, 0, 0, 255)
첫 번째 색상의 R 값: 255
마지막 색상의 Alpha 값: 128


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
