<a href="https://colab.research.google.com/github/Dain777666/ESAA_25-1/blob/main/YB0307_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [2]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print("5x3_matrix:\n", A)
print("3x2_matrix:\n", B)
result = np.dot(A,B)
print(result)

#real matrix product: 실수 행렬 간의 곱셉

[[0.29344278 0.55423609 0.15863519]
 [0.20350482 0.48112652 0.06501713]
 [0.77566579 0.60305058 0.12266291]
 [0.00386698 0.43138156 0.15468675]
 [0.68792841 0.8522226  0.20720024]]
[[0.15010816 0.35843434]
 [0.33453812 0.53786739]
 [0.32901671 0.4721865 ]]
[[0.28165488 0.47819088]
 [0.21289462 0.36242559]
 [0.35853532 0.66030627]
 [0.19578857 0.30645313]
 [0.45653696 0.80279707]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
import numpy as np

A = np.arange(11)
A[(A > 3) & (A < 8)] *= -1 # 3과 8 사이 (3 < x < 8)인 요소만 음수로 변환
print(A)

#3과 8 사이에 있는 모든 요소를 음수로 바꾸되, 원래 배열에서 직접 수정하라.

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#기본 sum()함수에서 두 번째 인수(start=-1)는 초기값을 의미

#NumPy의 sum()함수는 기본 sum()과 다르게 동작함
#sum(a, axis) 형식으로 사용됨
#range(5)는 [0, 1, 2, 3, 4]를 반환하는 1차원 리스트이므로, sum(range(5), -1)에서 -1은 축(axis) 인자로 해석됨

<축(axis) 개념 이해>

NumPy에서는 다차원 배열(ND-array) 을 다룰 때 축(axis)을 사용해 연산 방향을 지정해.

1차원 배열 (벡터) → 축(axis) 개념이 거의 없음.


2차원 배열 (행렬) → 행과 열이 있음.

axis=0 → 세로 방향(행 기준) 합산 (열 단위로 합)
axis=1 → 가로 방향(열 기준) 합산 (행 단위로 합)
3차원 이상 → 마지막 축(axis=-1)을 따라 합산

9 ( -1+0+1+2+3+4)
10 (0+1+2+3+4)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#정수 벡터 Z가 주어졌을 때, 다음 표현식(expression) 중 어떤 것이 유효한(합법적인)지 고려하라.

In [4]:
Z=np.arange(9).reshape(3,3)
#legal
print(Z**Z) #유효
print(2 << Z >> 2) #유효
print(Z <- Z) #Z < -Z 로 해석됨
print(1j*Z) #1j * Z는 정수 벡터 Z의 모든 요소를 허수로 변환
print(Z/1/1) #Z를 1로 나눈 후 다시 1로 나누는 것 #나눗셈을 하면 실수 배열로 변환
# Z<Z>Z -> X illegal   < 마지막 것이 올바르지 않은 표현이다!
#Z < Z 결과가 False 배열이므로 False > Z 같은 비교는 성립하지 않아 오류가 발생함

[[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]
[[  0   1   2]
 [  4   8  16]
 [ 32  64 128]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [5]:
print(np.array(0) / np.array(0))   # 결과 : nan
print(np.array(0) // np.array(0))   # 결과 : 0에 가까운 수
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-5-683be1b67b85>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))   # 결과 : nan
<ipython-input-5-683be1b67b85>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))   # 결과 : 0에 가까운 수
<ipython-input-5-683be1b67b85>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [7]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))
#np.intersect1d()는 두 배열의 공통 요소(교집합)를 반환하는 NumPy 함수

[1 8 0 9 5 4 0 6 3 9]
[0 7 2 7 7 6 6 0 5 9]
[0 5 6 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#NumPy의 sqrt()는 기본적으로 실수(real number) 연산을 수행
#실수 범위에서 음수의 제곱근은 정의되지 않으므로 nan(Not a Number)이 반환됨

#NumPy의 emath.sqrt()는 항상 복소수(complex number) 연산을 수행
#emath.sqrt(-1)는 복소수 연산이 가능하므로 1j를 반환

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [8]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B) #out=B 옵션이 있으므로 결과를 B에 저장
np.divide(A,2,out=A) #A를 2로 나눈 값
np.negative(A,out=A) #A의 부호를 반전
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [10]:
Z = np.random.uniform(0,10,10) #0과 10 사이에서 균등하게 분포된(uniform) 실수 10개 생성

print(Z - Z%1)
#각 원소에서 1로 나눈 나머지(소수점 이하 부분) 를 구함
#Z - Z % 1 → 소수 부분을 제거하여 정수 부분만 남김
print(Z // 1)
#Z // 1 → Z를 1로 나눈 후 소수 부분을 버리고 정수 부분만 반환

[9. 4. 8. 8. 6. 6. 7. 2. 2. 5.]
[9. 4. 8. 8. 6. 6. 7. 2. 2. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
A=np.random.randint(0,5,25).reshape((5,5))
print(A)

[[2 3 3 4 4]
 [4 3 0 2 0]
 [4 4 1 1 3]
 [3 1 2 3 3]
 [3 3 3 1 1]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [13]:
A=np.random.random(10)
print(A)
print(np.sort(A))

[0.57807987 0.35819921 0.51714203 0.01457331 0.0172896  0.84860378
 0.21757117 0.86402827 0.9624281  0.04731656]
[0.01457331 0.0172896  0.04731656 0.21757117 0.35819921 0.51714203
 0.57807987 0.84860378 0.86402827 0.9624281 ]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [15]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.65080533 0.70753276 0.25376493 0.81807132 0.90869827 0.19886674
 0.81493884 0.90613569 0.52932579 0.87914418]
[1.19133882 1.35410301 1.07634294 1.19339793 1.50952112 0.88385651
 0.68379264 0.87034327 1.15058868 1.10018615]


In [ ]:
#주어진 코드에서 10x2 크기의 랜덤 행렬을 생성한 후, 이를 직교 좌표계(Cartesian Coordinates)에서 극 좌표계(Polar Coordinates)로 변환
#직교 좌표계: (x, y) → x축과 y축으로 위치를 나타냄
#극 좌표계: (r, θ) → 원점(0,0)에서의 거리 r 과 x축과 이루는 각도 θ 로 나타냄


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [16]:
Z=np.random.randint(0,10,10)
Z[Z.argmax()]=0
print(Z)

[3 4 4 0 1 5 2 7 0 3]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [17]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()     #Z-v의 절댓값의 array의 가장 작은 값의 index return
print(Z[index])


18


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [18]:
Z = np.arange(9).reshape(3,3)
# 방법1
for index, value in np.ndenumerate(Z): #np.ndenumerate(): 인덱스와 값을 함께 가져올 때 사용
    print(index, value)
# 방법2
for index in np.ndindex(Z.shape): #인덱스만 반환 (값은 따로 접근)
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
#2D 배열에서 무작위로 p개의 요소를 배치하는 방법

In [ ]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
# np.random.choice(range(n*n), p, replace=False)
# → 0부터 n*n-1까지 중에서 p개의 랜덤한 위치 선택 (중복 없음)
# np.put(Z, 선택된 위치, 8) → 해당 위치에 8을 삽입
print(Z)

[[0. 0. 0.]
 [0. 0. 8.]
 [0. 0. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
#배열을 특정 열 기준으로 정렬하는 방법

In [19]:
# column 1
Z = np.random.randint(0,10,(3,3)) ## 0~9 사이의 정수로 3x3 랜덤 배열 생성

print(Z)
print(Z[Z[:,0].argsort()]) #첫 번째 열(column 0) 기준 정렬

[[4 3 2]
 [0 2 9]
 [1 8 4]]
[[0 2 9]
 [1 8 4]
 [4 3 2]]


In [20]:
# column 2
print(Z)
print(Z[Z[:,1].argsort()]) # 두 번째 열(column 1) 기준 정렬

[[4 3 2]
 [0 2 9]
 [1 8 4]]
[[0 2 9]
 [4 3 2]
 [1 8 4]]


In [21]:
# column 3
print(Z)
print(Z[Z[:,2].argsort()]) # 세 번째 열(column 2) 기준 정렬

[[4 3 2]
 [0 2 9]
 [1 8 4]]
[[4 3 2]
 [1 8 4]
 [0 2 9]]
